name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron:  '0 23 * * *'

jobs:
  install-lint-bandit-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup Python environment
      uses: actions/setup-python@v1.1.1
      with:
        python-version: '3.8'
    - name: Install
      run: pip install -r requirements.txt
    - name: Lint
      run: pylint app/
    - name: Bandit
      run: bandit -r app/
    - name: Test
      run: pytest
    - name: Coverage Report
      run: coverage run --source=tests/ -m pytest; coverage xml; coverage report
    - name: Code Coverage - CodeClimate
      uses: paambaati/codeclimate-action@v2.3.0
      env:
        CC_TEST_REPORTER_ID: ${{secrets.CODE_CLIMATE_TOKEN}}
      with:
        debug: true
